name: Release to Dev Environment

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push to Humanitec - Github Tag
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN_HUMANITEC_LABS }}
        organization: humanitec-labs
        file: Dockerfile-publish
        auto-tag: true

  docs-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push to Humanitec - Github Tag
      uses: humanitec/build-push-to-humanitec@v1
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
        organization: documentation
        file: Dockerfile-publish
        auto-tag: true
